import React from 'react';
import { useLocation, Navigate } from 'react-router-dom';
import SeoLandingTemplate, { SeoLandingData } from '../../components/seo/SeoLandingTemplate';

/**
 * DynamicFlatSeoPage — renders any registry-backed landing page.
 *
 * PERFORMANCE NOTE
 * ----------------
 * This previously did `import newSeoPagesData from '../../data/newSeoPagesData.json'`,
 * which pulled the entire 2 MB registry into one chunk. Vite emitted 1.7 MB of
 * JavaScript that all ~300 landing pages had to download and parse before
 * rendering — a direct hit to LCP and INP on mobile.
 *
 * The registry is now split into one JSON file per slug at prebuild time
 * (generate-sitemap.cjs → src/data/seoPages/), and `import.meta.glob` gives Vite
 * a separate chunk per page. A page now loads only its own few KB.
 *
 * Crawlers are unaffected either way: api/seo.js server-renders the full content
 * into the HTML before any of this JavaScript runs.
 *
 * src/data/seoPages/ is gitignored and regenerated by `npm run prebuild`
 * (and `npm run predev`), so it cannot go stale.
 */

// Lazy — each match becomes its own chunk rather than being bundled in.
const pageModules = import.meta.glob('../../data/seoPages/*.json');

/** URL slug → the flattened filename used on disk. */
function moduleKeyFor(slug: string): string {
  return `../../data/seoPages/${slug.replace(/\//g, '__')}.json`;
}

export default function DynamicFlatSeoPage() {
  const { pathname } = useLocation();
  const slug = pathname.toLowerCase().replace(/^\/+|\/+$/g, '');

  const [data, setData] = React.useState<SeoLandingData | null>(null);
  const [missing, setMissing] = React.useState(false);

  React.useEffect(() => {
    let cancelled = false;
    setData(null);
    setMissing(false);

    const loader = pageModules[moduleKeyFor(slug)];
    if (!slug || !loader) {
      setMissing(true);
      return;
    }

    loader()
      .then((mod: any) => {
        if (!cancelled) setData((mod.default || mod) as SeoLandingData);
      })
      .catch(() => {
        if (!cancelled) setMissing(true);
      });

    return () => { cancelled = true; };
  }, [slug]);

  if (missing) return <Navigate to="/not-found" replace />;

  // Brief placeholder while the page's own chunk loads. The server-rendered
  // markup is already in the document, so crawlers never see this.
  if (!data) {
    return (
      <div
        style={{
          minHeight: '60vh', display: 'flex', alignItems: 'center',
          justifyContent: 'center', background: 'var(--bg-primary)',
        }}
        aria-busy="true"
      >
        <div
          style={{
            width: 34, height: 34, border: '3px solid var(--border-light)',
            borderTopColor: 'var(--accent-primary)', borderRadius: '50%',
            animation: 'spin 0.9s linear infinite',
          }}
        />
      </div>
    );
  }

  return <SeoLandingTemplate data={data} />;
}
