// AUTO-GENERATED by generate-sitemap.cjs — do not edit.
// Source of truth: src/data/blogFormat.js

/**
 * blogFormat.js — turn whatever the CMS stored into clean, semantic article HTML.
 *
 * THE PROBLEM
 * -----------
 * Blog bodies arrive in three different shapes, and the page rendered all of
 * them as flat text:
 *
 *   • 34 posts are proper HTML (<p>, <h2>, <h3>, <ul>, <strong>) but nothing
 *     styled them — headings, lists and tables inherited the paragraph style,
 *     so a well-structured article looked like an undifferentiated wall.
 *   • 18 posts contain NO markup at all — newline-separated plain text, with
 *     the title repeated as the first line.
 *   • 10 contain markdown syntax (## headings, - lists, | tables |).
 *
 * Plus 1,583 editor-injected `<span style="background-color: transparent;">`
 * wrappers that add noise.
 *
 * WHAT THIS DOES
 * --------------
 * Normalises all three into the same semantic HTML — h2/h3, ul/ol, table,
 * blockquote, strong, em, code — which the prose stylesheet then styles. Then:
 *
 *   • wraps "Key takeaways" and "Frequently asked questions" in callout cards
 *   • auto-links the first mention of each service to its money page, so posts
 *     pass authority to the pages that need to rank instead of dead-ending
 *
 * Used by BOTH the React page and api/seo.js, so what a reader sees and what
 * Googlebot indexes are the same markup.
 *
 * Import-free so the serverless function can consume it.
 */

/* DATA-START */

/** Escape text destined for HTML. */
function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Inline markdown → HTML. Applied to already-escaped text. */
function inline(text) {
  return String(text)
    // `code`
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    // **bold** and __bold__
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/__([^_]+)__/g, '<strong>$1</strong>')
    // *italic* — avoid matching bold leftovers
    .replace(/(^|[^*])\*([^*\n]+)\*($|[^*])/g, '$1<em>$2</em>$3')
    // [label](href)
    .replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, '<a href="$2">$1</a>');
}

/** A stable id for a heading, so it can be linked and cited. */
function slugifyHeading(text) {
  return String(text)
    .toLowerCase()
    .replace(/<[^>]+>/g, '')
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 60);
}

/** True when the body already contains block-level HTML worth preserving. */
function looksLikeHtml(s) {
  return /<(p|h1|h2|h3|h4|ul|ol|li|table|blockquote|div|section)\b/i.test(String(s || ''));
}

/**
 * Clean HTML that the editor produced: drop no-op spans, demote stray H1s so the
 * page keeps exactly one, and give headings ids.
 */
function cleanHtml(html) {
  let s = String(html || '');

  // Editor noise: <span style="background-color: transparent;">…</span> and
  // empty spans/divs contribute nothing and complicate styling.
  s = s.replace(/<span[^>]*background-color:\s*transparent[^>]*>/gi, '');
  s = s.replace(/<span\s*>/gi, '');
  s = s.replace(/<\/span>/gi, '');

  // Inline colour/background baked in by whichever editor produced the post
  // will not match this stylesheet, so strip presentational attributes.
  s = s.replace(/\s(?:style|bgcolor|color|face)="[^"]*"/gi, '');
  s = s.replace(/\s(?:style|bgcolor|color|face)='[^']*'/gi, '');

  // Exactly one H1 per page — the article title. Anything else becomes an H2.
  s = s.replace(/<h1(\s[^>]*)?>/gi, '<h2$1>').replace(/<\/h1>/gi, '</h2>');

  // Drop empty paragraphs left behind by the editor.
  s = s.replace(/<p>\s*(&nbsp;)?\s*<\/p>/gi, '');

  // Heading ids for anchor links and citation.
  s = s.replace(/<(h2|h3|h4)([^>]*)>([\s\S]*?)<\/\1>/gi, (m, tag, attrs, body) => {
    if (/\bid=/.test(attrs)) return m;
    return `<${tag}${attrs} id="${slugifyHeading(body)}">${body}</${tag}>`;
  });

  return s.trim();
}

/**
 * Markdown / plain text → semantic HTML.
 *
 * Deliberately small rather than pulling in a markdown library: the serverless
 * function ships this file, and the subset actually used by these posts is
 * headings, lists, tables, blockquotes and emphasis.
 */
function markdownToHtml(src, opts) {
  const options = opts || {};
  let text = String(src || '').replace(/\r\n/g, '\n');

  // The plain-text posts use a single newline per paragraph and contain no
  // blank lines at all. Without this, every line accumulates into one enormous
  // paragraph — which is exactly how these posts were rendering.
  if (!/\n\s*\n/.test(text)) text = text.replace(/\n/g, '\n\n');

  const lines = text.split('\n');
  const out = [];

  let i = 0;
  let firstHeadingUsed = false;

  const flushParagraph = (buf) => {
    if (!buf.length) return;
    out.push(`<p>${inline(esc(buf.join(' ').trim()))}</p>`);
    buf.length = 0;
  };

  const para = [];

  while (i < lines.length) {
    const line = lines[i];
    const trimmed = line.trim();

    // Blank line ends a paragraph.
    if (!trimmed) { flushParagraph(para); i++; continue; }

    // Fenced code block
    if (/^```/.test(trimmed)) {
      flushParagraph(para);
      const lang = trimmed.replace(/^```/, '').trim();
      const buf = [];
      i++;
      while (i < lines.length && !/^```/.test(lines[i].trim())) { buf.push(lines[i]); i++; }
      i++; // closing fence
      out.push(`<pre><code${lang ? ` class="language-${esc(lang)}"` : ''}>${esc(buf.join('\n'))}</code></pre>`);
      continue;
    }

    // ATX heading
    const atx = trimmed.match(/^(#{1,4})\s+(.*)$/);
    if (atx) {
      flushParagraph(para);
      // Never emit H1 — the page title owns it.
      const level = Math.max(2, atx[1].length);
      const text = inline(esc(atx[2].trim()));
      out.push(`<h${level} id="${slugifyHeading(atx[2])}">${text}</h${level}>`);
      firstHeadingUsed = true;
      i++; continue;
    }

    // Markdown table: | a | b |  /  |---|---|
    //
    // The separator row is found by skipping blanks, not by looking at i+1: the
    // "no blank lines" normalisation above inserts one between every line, which
    // would otherwise put a blank row between the header and the separator and
    // stop any table in such a post from ever being recognised.
    let sep = i + 1;
    while (sep < lines.length && !lines[sep].trim()) sep++;
    if (/^\|/.test(trimmed) && sep < lines.length && /^\|?[\s:-]*[-]{2,}[\s:|-]*$/.test(lines[sep].trim())) {
      flushParagraph(para);
      const cells = (row) => row.trim().replace(/^\||\|$/g, '').split('|').map((c) => c.trim());
      const head = cells(trimmed);
      i = sep + 1;
      const body = [];
      while (i < lines.length) {
        if (!lines[i].trim()) { i++; continue; }   // skip inserted blank rows
        if (!/^\|/.test(lines[i].trim())) break;
        body.push(cells(lines[i])); i++;
      }
      out.push(
        '<div class="prose-table-wrap"><table>' +
        '<thead><tr>' + head.map((h) => `<th>${inline(esc(h))}</th>`).join('') + '</tr></thead>' +
        '<tbody>' + body.map((r) => '<tr>' + r.map((c) => `<td>${inline(esc(c))}</td>`).join('') + '</tr>').join('') +
        '</tbody></table></div>'
      );
      continue;
    }

    // Blockquote
    if (/^>\s?/.test(trimmed)) {
      flushParagraph(para);
      const buf = [];
      while (i < lines.length && /^>\s?/.test(lines[i].trim())) {
        buf.push(lines[i].trim().replace(/^>\s?/, '')); i++;
      }
      out.push(`<blockquote><p>${inline(esc(buf.join(' ')))}</p></blockquote>`);
      continue;
    }

    // Unordered list
    if (/^[-*•]\s+/.test(trimmed)) {
      flushParagraph(para);
      const items = [];
      while (i < lines.length && /^[-*•]\s+/.test(lines[i].trim())) {
        items.push(lines[i].trim().replace(/^[-*•]\s+/, '')); i++;
      }
      out.push('<ul>' + items.map((t) => `<li>${inline(esc(t))}</li>`).join('') + '</ul>');
      continue;
    }

    // Ordered list
    if (/^\d+[.)]\s+/.test(trimmed)) {
      flushParagraph(para);
      const items = [];
      while (i < lines.length && /^\d+[.)]\s+/.test(lines[i].trim())) {
        items.push(lines[i].trim().replace(/^\d+[.)]\s+/, '')); i++;
      }
      out.push('<ol>' + items.map((t) => `<li>${inline(esc(t))}</li>`).join('') + '</ol>');
      continue;
    }

    // Plain-text posts repeat the article title as the first line. Drop it so
    // the page does not show the heading twice.
    if (!firstHeadingUsed && options.title && !para.length && out.length === 0) {
      const norm = (x) => String(x).toLowerCase().replace(/[^a-z0-9]/g, '');
      if (norm(trimmed) === norm(options.title) || norm(options.title).startsWith(norm(trimmed).slice(0, 40))) {
        firstHeadingUsed = true; i++; continue;
      }
    }

    // A short line with no terminal punctuation, followed by prose, is almost
    // always a section heading in these plain-text posts. Look ahead to the next
    // NON-EMPTY line — paragraphs here are separated by blank lines, so the
    // immediately following line is usually blank.
    let n = i + 1;
    while (n < lines.length && !lines[n].trim()) n++;
    const next = (lines[n] || '').trim();

    // A run of consecutive short lines is a list, not a series of headings —
    // several posts contain bare keyword lists that would otherwise all become
    // H2s. Require the preceding block to be prose (or the start of the post).
    let prev = i - 1;
    while (prev >= 0 && !lines[prev].trim()) prev--;
    const prevLine = prev >= 0 ? lines[prev].trim() : '';
    const prevWasProse = !prevLine || prevLine.length > 60;

    const looksLikeHeading =
      trimmed.length < 90 &&
      // A trailing "?" is allowed — question-form headings ("Which sourcing
      // channels give the best value?") are the norm in these posts and were
      // previously demoted to paragraphs by excluding it.
      !/[.!,;:]$/.test(trimmed) &&
      next.length > 0 &&
      // The following block must be prose, not another short line.
      next.length > 60 &&
      prevWasProse &&
      !/^[-*•\d]/.test(trimmed) &&
      /^[A-Z0-9]/.test(trimmed) &&
      trimmed.split(' ').length <= 12;

    if (looksLikeHeading && !para.length) {
      out.push(`<h2 id="${slugifyHeading(trimmed)}">${inline(esc(trimmed))}</h2>`);
      firstHeadingUsed = true;
      i++; continue;
    }

    para.push(trimmed);
    i++;
  }

  flushParagraph(para);
  return out.join('\n');
}

/* ── Internal linking ─────────────────────────────────────────────────────── */

/**
 * First mention of each service becomes a link to the page that sells it.
 *
 * Posts previously dead-ended: 65,000 words of content passing no authority to
 * the pages that actually need to rank, and no route from a reader who has just
 * been convinced to the page where they can act on it.
 *
 * Order matters — the most specific phrase must be tested first, or "AI" would
 * swallow "AI chatbot". Each destination is used at most once per post, and the
 * whole post is capped, because a paragraph peppered with links reads as spam
 * to both people and Google.
 */
const INTERNAL_LINKS = [
  [/\bAI chatbots?\b/i, '/ai-chatbot-development'],
  [/\bvoice (?:agents?|bots?)\b/i, '/ai-chatbot-development'],
  [/\bAI (?:agents?|automation)\b/i, '/ai-automation-company'],
  [/\bagentic AI\b/i, '/ai-automation-company'],
  [/\bAI (?:solutions?|development|consulting)\b/i, '/ai-development-company'],
  [/\bsocial media marketing\b/i, '/social-media-marketing-company'],
  [/\bdigital marketing\b/i, '/digital-marketing-company'],
  [/\bsearch engine optimisation\b/i, '/seo-company'],
  [/\bSEO\b/, '/seo-company'],
  [/\b(?:web|website) (?:development|design)\b/i, '/web-development-company'],
  [/\be-?commerce (?:development|website|store)\b/i, '/ecommerce-development-company'],
  [/\bpodcast production\b/i, '/podcast-production-company'],
  [/\bBusiness OS\b/, '/business-os'],
];

const MAX_AUTO_LINKS = 6;

/**
 * Add internal links to body HTML, skipping anything already linked, any
 * heading, and any code.
 *
 * Works on the HTML string rather than a DOM because api/seo.js runs this in a
 * serverless function with no document available.
 */
function autoLinkBody(html, opts) {
  const options = opts || {};
  const selfPath = options.selfPath || '';
  let added = 0;
  const used = new Set();

  // Seed with destinations the author already linked by hand, so a post that
  // links /seo-company in its intro does not get a second automatic one.
  const existing = html.match(/href="(\/[^"]*)"/g) || [];
  existing.forEach((h) => used.add(h.slice(6, -1)));

  // Regions we must not touch: existing links, headings, code, and raw tags.
  const PROTECTED = /(<a\b[^>]*>[\s\S]*?<\/a>|<(h[1-6]|code|pre)\b[^>]*>[\s\S]*?<\/\2>|<[^>]+>)/gi;

  const linkifyText = (text) => {
    if (added >= MAX_AUTO_LINKS) return text;
    let out = text;
    for (const [pattern, href] of INTERNAL_LINKS) {
      if (added >= MAX_AUTO_LINKS) break;
      if (used.has(href) || href === selfPath) continue;
      // Rebuild non-global so replace() only touches the first match.
      const re = new RegExp(pattern.source, pattern.flags.replace('g', ''));
      if (!re.test(out)) continue;
      out = out.replace(re, (m) => `<a href="${href}" class="prose-inline-link">${m}</a>`);
      used.add(href);
      added++;
    }
    return out;
  };

  let result = '';
  let last = 0;
  let match;
  PROTECTED.lastIndex = 0;
  while ((match = PROTECTED.exec(html)) !== null) {
    result += linkifyText(html.slice(last, match.index));
    result += match[0];
    last = match.index + match[0].length;
  }
  result += linkifyText(html.slice(last));
  return result;
}

/* ── Callouts ─────────────────────────────────────────────────────────────── */

/**
 * Promote "Key takeaways" and "Frequently asked questions" from plain headings
 * to visually distinct cards. Both are the sections readers skim and AI engines
 * quote, so they earn the emphasis.
 */
function wrapCallouts(html) {
  let s = html;

  // "Key takeaways" heading + the list that follows it.
  s = s.replace(
    /<h2([^>]*)>\s*(key takeaways?|takeaways?|tl;?dr)\s*<\/h2>\s*(<ul>[\s\S]*?<\/ul>)/gi,
    (m, attrs, label, list) =>
      `<div class="prose-callout"><h2${attrs} class="prose-callout-title">${label}</h2>${list}</div>`
  );

  // FAQ section: mark the heading so the stylesheet can space the Q&A pairs.
  s = s.replace(
    /<h2([^>]*)>\s*(frequently asked questions|faqs?)\s*<\/h2>/gi,
    (m, attrs, label) => `<h2${attrs} class="prose-faq-title">${label}</h2>`
  );

  return s;
}

/**
 * The single entry point. Returns semantic HTML ready for the prose styles.
 *
 * opts: { title, selfPath, autoLink }
 */
function formatBlogBody(raw, opts) {
  const options = opts || {};
  const src = String(raw || '').trim();
  if (!src) return '';
  let html = looksLikeHtml(src) ? cleanHtml(src) : markdownToHtml(src, options);

  // Several posts open with a heading that repeats the article title, so the
  // page showed the same words twice. Drop a leading heading when it matches.
  const title = options.title;
  if (title) {
    const norm = (x) => String(x).toLowerCase().replace(/<[^>]+>/g, '').replace(/[^a-z0-9]/g, '');
    html = html.replace(/^\s*<(h2|h3)[^>]*>([\s\S]*?)<\/\1>/i, (m, tag, body) => {
      const a = norm(body);
      const b = norm(title);
      if (!a || !b) return m;
      return a === b || b.startsWith(a.slice(0, 40)) || a.startsWith(b.slice(0, 40)) ? '' : m;
    }).trim();
  }

  if (options.autoLink !== false) html = autoLinkBody(html, options);
  html = wrapCallouts(html);

  return html;
}

/**
 * Article typography — a light reading surface on a dark site.
 *
 * The article is deliberately a distinct "document" surface rather than more
 * dark chrome: long-form body copy is measurably easier to read as dark-on-light,
 * and it matches the Business OS blog this was modelled on. Colours are literal
 * rather than var()-driven precisely so the dark theme's variables cannot leak
 * in and produce grey-on-cream.
 *
 * Scoped to .prose so it cannot affect the rest of the site.
 */
const PROSE_CSS = `
.prose {
  --ink:        #1A1714;
  --ink-body:   #3A352E;
  --ink-muted:  #6B635A;
  --rule:       #E7E0D5;
  --paper:      #FFFDF9;
  --accent:     #A87613;
  --accent-bg:  #FBF4E3;

  max-width: 44rem;
  font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
  font-size: 1.075rem;
  line-height: 1.78;
  color: var(--ink-body);
  letter-spacing: -0.003em;
}
.prose > * + * { margin-top: 1.3em; }

.prose h2 {
  font-family: 'Outfit', 'Inter', sans-serif;
  font-size: clamp(1.4rem, 2.7vw, 1.75rem);
  font-weight: 700;
  line-height: 1.28;
  letter-spacing: -0.022em;
  color: var(--ink);
  margin-top: 2.5em;
  margin-bottom: 0.65em;
}
.prose h2:first-child { margin-top: 0; }
.prose h3 {
  font-family: 'Outfit', 'Inter', sans-serif;
  font-size: 1.2rem; font-weight: 700; line-height: 1.35;
  letter-spacing: -0.015em;
  color: var(--ink);
  margin-top: 2em; margin-bottom: 0.5em;
}
.prose h4 {
  font-family: 'Outfit', 'Inter', sans-serif;
  font-size: 1.02rem; font-weight: 700;
  color: var(--ink);
  margin-top: 1.7em; margin-bottom: 0.4em;
}
.prose p { margin: 0; }
.prose strong { color: var(--ink); font-weight: 650; }
.prose em { font-style: italic; }

.prose a {
  color: var(--accent);
  font-weight: 500;
  text-decoration: underline;
  text-decoration-color: rgba(168,118,19,0.42);
  text-underline-offset: 3px;
  text-decoration-thickness: 1.5px;
  transition: text-decoration-color 0.15s, color 0.15s;
}
.prose a:hover { color: #8A5F0C; text-decoration-color: currentColor; }

.prose ul, .prose ol { padding-left: 1.4em; margin: 1.3em 0; }
.prose ul { list-style: disc; }
.prose ol { list-style: decimal; }
.prose li { margin: 0.55em 0; padding-left: 0.3em; }
.prose li::marker { color: var(--accent); }
.prose li > ul, .prose li > ol { margin: 0.55em 0; }

/* Key takeaways — the block readers skim and AI engines quote. */
.prose .prose-callout {
  background: var(--accent-bg);
  border: 1px solid #EBDCB6;
  border-radius: 14px;
  padding: 24px 26px;
  margin: 2em 0;
}
.prose .prose-callout-title {
  font-size: 0.8rem !important;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.09em;
  color: var(--accent) !important;
  margin: 0 0 0.9em 0 !important;
}
.prose .prose-callout ul { margin: 0; padding-left: 1.2em; }
.prose .prose-callout li { margin: 0.5em 0; color: var(--ink-body); }
.prose .prose-faq-title { padding-top: 0.4em; border-top: 2px solid var(--rule); }

.prose blockquote {
  margin: 1.9em 0;
  padding: 0.1em 0 0.1em 1.3em;
  border-left: 3px solid var(--accent);
  color: var(--ink);
  font-size: 1.1rem;
  font-style: italic;
}
.prose blockquote p { margin: 0; }

.prose code {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 0.87em;
  background: #F4F1EA;
  border: 1px solid var(--rule);
  border-radius: 5px;
  padding: 0.15em 0.4em;
  color: #7A3E00;
}
.prose pre {
  background: #1E1B16;
  border-radius: 12px;
  padding: 18px 20px;
  overflow-x: auto;
  margin: 1.8em 0;
}
.prose pre code {
  background: none; border: none; padding: 0;
  color: #EDE6D8; font-size: 0.86rem; line-height: 1.65;
}

/* Tables scroll inside their own container so the page never scrolls sideways */
.prose .prose-table-wrap { overflow-x: auto; margin: 1.9em 0; }
.prose table { width: 100%; border-collapse: collapse; min-width: 460px; font-size: 0.97rem; }
.prose th {
  text-align: left; padding: 11px 16px 11px 0; font-weight: 700;
  font-size: 0.95rem; color: var(--ink);
  border-bottom: 2px solid var(--rule);
  white-space: nowrap;
}
.prose td {
  padding: 13px 16px 13px 0; vertical-align: top;
  color: var(--ink-body);
  border-bottom: 1px solid var(--rule);
}
.prose th:last-child, .prose td:last-child { padding-right: 0; }
.prose tbody tr:last-child td { border-bottom: none; }

.prose img { max-width: 100%; height: auto; border-radius: 12px; margin: 1.9em 0; }
.prose hr { border: none; border-top: 1px solid var(--rule); margin: 2.6em 0; }

@media (max-width: 640px) {
  .prose { font-size: 1.02rem; line-height: 1.72; }
  .prose h2 { font-size: 1.32rem; margin-top: 2.1em; }
  .prose .prose-callout { padding: 20px; border-radius: 12px; }
}
`;

/* DATA-END */

export {
  formatBlogBody, cleanHtml, markdownToHtml, slugifyHeading, looksLikeHtml,
  autoLinkBody, wrapCallouts, PROSE_CSS, esc, inline,
};
