// AUTO-GENERATED by generate-sitemap.cjs — do not edit.
// Source of truth: src/data/offices.js

/**
 * offices.js — single source of truth for Avani Enterprises NAP data.
 *
 * WHY THIS EXISTS
 * ---------------
 * The codebase carried THREE different Gurugram addresses:
 *   1. Footer.tsx          "3rd Floor, Tower-B, Cyber Park, Durga Colony,
 *                           Sector 39, Gurugram, Haryana 122001"
 *   2. website-content.md  "Tower B, 3rd Floor, Unitech Cyber Park, Sector 39,
 *                           Gurugram, Haryana 122002"   (same building, different PIN)
 *   3. LocalServicePage /  "DLF Cyber City, Gurugram"    (a DIFFERENT part of the city)
 *      cityPagesData.ts
 * …and the phone number appeared in five formats.
 *
 * NAP (Name, Address, Phone) consistency is a direct local-pack ranking factor:
 * Google cross-references your website against your Google Business Profile and
 * third-party citations, and conflicting addresses suppress local rankings. One
 * file now owns this, and everything else reads from it.
 *
 * THE `confirmed` FLAG — READ BEFORE CHANGING
 * -------------------------------------------
 * Claiming a location you do not physically staff is how Google Business
 * Profiles get suspended, and a suspension is far harder to undo than it is to
 * avoid. So this file distinguishes two things:
 *
 *   confirmed: true   A real, staffed premises. Gets a visible address, a map,
 *                     LocalBusiness schema, and GBP-oriented copy.
 *   confirmed: false  A market we sell into and deliver to remotely. Gets
 *                     organic "serving {city}" copy ONLY — no address, no map,
 *                     no LocalBusiness schema, and no prose claiming an office.
 *
 * Only Gurugram is currently `confirmed`, because it is the only location whose
 * address the client has verified. Everything else is sell-only until confirmed
 * in writing. Do NOT flip `confirmed` to true to make a page look stronger —
 * the page ranking slightly better is not worth a GBP suspension.
 *
 * Note the `candidateAddress` field: an address found elsewhere in the codebase
 * that MIGHT be real but has not been confirmed. It is never rendered. It exists
 * so the client can confirm or reject it rather than us guessing.
 */

/* DATA-START */

const NAP = {
  name: 'Avani Enterprises',
  url: 'https://www.avanienterprises.in',
  // One canonical phone format everywhere. E.164 for tel:/schema, spaced for display.
  phone: '+919253625099',
  phoneDisplay: '+91 92536 25099',
  email: 'kp@avanienterprises.in',
  sameAs: [
    'https://www.linkedin.com/company/avani-enterprises-india',
    'https://www.instagram.com/avanienterprises.branding/',
    'https://twitter.com/avanienterprises',
    'https://www.facebook.com/share/1DKFWQiBe4/',
  ],
  openingHours: {
    days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    opens: '09:00',
    closes: '19:00',
  },
};

const OFFICES = {
  gurgaon: {
    key: 'gurgaon',
    city: 'Gurugram',
    label: 'Gurugram (Head Office)',
    isHQ: true,
    // ⚠️ Address itself still needs client confirmation — three conflicting
    // versions existed. This is the Footer version. Confirmed = "we agree a real
    // office exists here"; the street line may still change.
    confirmed: true,
    schemaReady: true,
    address: {
      street: '3rd Floor, Tower-B, Cyber Park, Durga Colony, Sector 39',
      locality: 'Gurugram',
      region: 'Haryana',
      postalCode: '122001',
      country: 'IN',
    },
    // Sector 39 / Cyber Park, Gurugram. Approximate to the building, not a survey point.
    geo: { lat: 28.4419, lng: 77.0483 },
    areasServed: ['Cyber City', 'Udyog Vihar', 'Golf Course Road', 'Sohna Road', 'Sector 39', 'MG Road', 'IMT Manesar'],
    localNote:
      'Our head office is on the Sector 39 Cyber Park side of Gurugram, a short drive from Cyber City and the Golf Course Road corridor, so client workshops and review sessions happen in person rather than over video.',
  },

  // ── SELL-ONLY MARKETS ─────────────────────────────────────────────────────
  // We sell into and deliver to these. We do NOT claim a physical office in any
  // of them until the client confirms a real, staffed premises in writing.
  // localNote copy below therefore describes delivery, never a location.
  noida: {
    key: 'noida',
    city: 'Noida',
    label: 'Noida',
    confirmed: false,
    schemaReady: false,
    address: null,
    areasServed: ['Sector 62', 'Sector 63', 'Sector 16A Film City', 'Sector 125–132 expressway corridor'],
    localNote:
      'We work with clients across the Sector 62–63 IT belt, Film City and the expressway corridor. Delivery is from our Gurugram head office, roughly an hour away, so on-site meetings are practical when a project needs them.',
  },
  rohtak: {
    key: 'rohtak',
    city: 'Rohtak',
    label: 'Rohtak',
    confirmed: false,
    schemaReady: false,
    address: null,
    // Found in GlobalPresenceComponent.tsx, GlobalPresenceSection.tsx and
    // home2/data.ts as "our founding office". NOT rendered anywhere until the
    // client confirms it is a real, currently-staffed premises.
    candidateAddress: '106, First Floor, Agro Mall, Rohtak, Haryana',
    areasServed: ['IMT Rohtak', 'Delhi Road commercial belt', 'Model Town', 'Sector 14 institutional area'],
    localNote:
      'We work with institutes, hospitals, IMT manufacturers and retailers across Rohtak. Delivery runs from our Gurugram head office, which is close enough that on-site sessions are straightforward.',
  },
  mumbai: {
    key: 'mumbai',
    city: 'Mumbai',
    label: 'Mumbai',
    confirmed: false,
    schemaReady: false,
    address: null,
    areasServed: ['Bandra Kurla Complex (BKC)', 'Lower Parel', 'Andheri East (MIDC and SEEPZ)', 'Powai'],
    localNote:
      'We work with BFSI, media and D2C clients across BKC, Lower Parel and Andheri East. Delivery is remote from our Gurugram head office, on IST alongside you, with travel for kickoff on larger engagements.',
  },
  dubai: {
    key: 'dubai',
    city: 'Dubai',
    label: 'Dubai',
    confirmed: false,
    schemaReady: false,
    international: true,
    currency: 'AED',
    address: null,
    areasServed: ['Business Bay', 'DMCC and Jumeirah Lakes Towers', 'Dubai Internet City', 'Deira'],
    localNote:
      'We work with real estate, trading, hospitality and logistics businesses across the Emirates. Delivery is from our India team — Dubai runs 1.5 hours behind IST, so the working day overlaps almost entirely, and we invoice in AED.',
  },
};

/** Offices we can legitimately publish an address and map for. */
function publishableOffices() {
  return Object.values(OFFICES).filter((o) => o.confirmed && o.schemaReady && o.address);
}

/** Confirmed, staffed premises — the only ones that may claim a location. */
function confirmedOffices() {
  return Object.values(OFFICES).filter((o) => o.confirmed);
}

/** True when we may make any "we have an office here" claim about this key. */
function hasConfirmedOffice(locationKey) {
  const o = officeFor(locationKey);
  return !!(o && o.confirmed);
}

/**
 * Human-readable list of confirmed office cities, for copy that would otherwise
 * hardcode "Gurugram, Noida, Rohtak, Mumbai and Dubai". Derived, so it shrinks
 * or grows automatically as offices are confirmed.
 */
function confirmedOfficeCities() {
  const cities = confirmedOffices().map((o) => o.city);
  if (cities.length === 0) return '';
  if (cities.length === 1) return cities[0];
  return cities.slice(0, -1).join(', ') + ' and ' + cities[cities.length - 1];
}

/** Look up an office by location key, following the gurugram/gurgaon alias. */
function officeFor(locationKey) {
  if (!locationKey) return null;
  const key = String(locationKey).toLowerCase() === 'gurugram' ? 'gurgaon' : String(locationKey).toLowerCase();
  return OFFICES[key] || null;
}

/** A Google Maps embed URL. Uses the query form so no API key is needed. */
function mapEmbedUrl(office) {
  if (!office || !office.address) return null;
  const a = office.address;
  const q = [a.street, a.locality, a.region, a.postalCode, 'India'].filter(Boolean).join(', ');
  return `https://www.google.com/maps?q=${encodeURIComponent(q)}&output=embed`;
}

/** A plain "get directions" link, safe to show even without an embed. */
function mapLinkUrl(office) {
  if (!office) return null;
  const a = office.address;
  const q = a
    ? [NAP.name, a.street, a.locality, a.region, a.postalCode].filter(Boolean).join(', ')
    : `${NAP.name} ${office.city}`;
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
}

/** Single-line address for display. Null when we have no verified address. */
function formatAddress(office) {
  if (!office || !office.address) return null;
  const a = office.address;
  return [a.street, a.locality, `${a.region} ${a.postalCode}`].filter(Boolean).join(', ');
}

/**
 * LocalBusiness JSON-LD for an office. Returns null unless we hold a verified
 * address — incomplete or invented LocalBusiness markup is worse than none.
 */
function localBusinessSchema(office, pageUrl) {
  // Three gates, all required. An unconfirmed location must never emit
  // LocalBusiness markup — that is what triggers GBP suspensions.
  if (!office || !office.confirmed || !office.schemaReady || !office.address) return null;
  const a = office.address;
  return {
    '@context': 'https://schema.org',
    '@type': 'ProfessionalService',
    '@id': `${NAP.url}/#office-${office.key}`,
    name: office.isHQ ? NAP.name : `${NAP.name} — ${office.city}`,
    url: pageUrl || NAP.url,
    telephone: NAP.phone,
    email: NAP.email,
    parentOrganization: { '@id': `${NAP.url}/#organization` },
    address: {
      '@type': 'PostalAddress',
      streetAddress: a.street,
      addressLocality: a.locality,
      addressRegion: a.region,
      postalCode: a.postalCode,
      addressCountry: a.country,
    },
    geo: office.geo
      ? { '@type': 'GeoCoordinates', latitude: office.geo.lat, longitude: office.geo.lng }
      : undefined,
    areaServed: (office.areasServed || []).map((n) => ({ '@type': 'Place', name: n })),
    openingHoursSpecification: [
      {
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: NAP.openingHours.days,
        opens: NAP.openingHours.opens,
        closes: NAP.openingHours.closes,
      },
    ],
    sameAs: NAP.sameAs,
    // Deliberately no aggregateRating — see SEO-RECOVERY.md §4.1.
  };
}

/* DATA-END */

export {
  NAP,
  OFFICES,
  officeFor,
  publishableOffices,
  confirmedOffices,
  confirmedOfficeCities,
  hasConfirmedOffice,
  mapEmbedUrl,
  mapLinkUrl,
  formatAddress,
  localBusinessSchema,
};
