// AUTO-GENERATED by generate-sitemap.cjs — do not edit.
// Source of truth: src/data/offices.js

/**
 * offices.js — single source of truth for Avani Enterprises NAP data.
 *
 * WHY THIS EXISTS
 * ---------------
 * The codebase carried three different Gurugram addresses and five phone
 * formats. All are now reconciled to the client-confirmed canonical below.
 *
 * NAP (Name, Address, Phone) consistency is a direct local-pack ranking factor:
 * Google cross-references your website against your Google Business Profile and
 * third-party citations, and conflicting addresses suppress local rankings. One
 * file now owns this, and everything else reads from it.
 *
 * Superseded variants, all now purged:
 *   1. Footer.tsx          an older Cyber Park variant with PIN 122001
 *   2. website-content.md  the same building without "Durga Colony"
 *   3. cityPagesData.ts /  "DLF Cyber City, Gurugram" — a different part of the
 *      LocalServicePage    city entirely, asserted as our HQ on 87 occasions
 *
 * DLF Cyber City still appears on some Gurugram pages as an area we serve.
 * That is accurate and intentional; only the HQ claims were wrong.
 *
 * THE `confirmed` FLAG — READ BEFORE CHANGING
 * -------------------------------------------
 * Claiming a location you do not physically staff is how Google Business
 * Profiles get suspended, and a suspension is far harder to undo than it is to
 * avoid. So this file distinguishes two things:
 *
 *   confirmed: true   A real, staffed premises. Gets a visible address, a map,
 *                     LocalBusiness schema, and GBP-oriented copy.
 *   confirmed: false  A market we sell into and deliver to remotely. Gets
 *                     organic "serving {city}" copy ONLY — no address, no map,
 *                     no LocalBusiness schema, and no prose claiming an office.
 *
 * Only Gurugram is currently `confirmed`, because it is the only location whose
 * address the client has verified. Everything else is sell-only until confirmed
 * in writing. Do NOT flip `confirmed` to true to make a page look stronger —
 * the page ranking slightly better is not worth a GBP suspension.
 *
 * Note the `candidateAddress` field: an address found elsewhere in the codebase
 * that MIGHT be real but has not been confirmed. It is never rendered. It exists
 * so the client can confirm or reject it rather than us guessing.
 */

/* DATA-START */

const NAP = {
  name: 'Avani Enterprises',
  url: 'https://www.avanienterprises.in',
  // One canonical phone format everywhere. E.164 for tel:/schema, spaced for display.
  phone: '+919253625099',
  phoneDisplay: '+91 92536 25099',
  email: 'kp@avanienterprises.in',
  sameAs: [
    'https://www.linkedin.com/company/avani-enterprises-india',
    'https://www.instagram.com/avanienterprises.branding/',
    'https://twitter.com/avanienterprises',
    'https://www.facebook.com/share/1DKFWQiBe4/',
  ],
  openingHours: {
    days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    opens: '09:00',
    closes: '19:00',
  },
};

const OFFICES = {
  gurgaon: {
    key: 'gurgaon',
    city: 'Gurugram',
    label: 'Gurugram (Head Office)',
    isHQ: true,
    // Client-confirmed. Supersedes the two variants that were in the codebase
    // Supersedes the earlier "DLF Cyber City" and alternate-PIN variants.
    confirmed: true,
    schemaReady: true,
    address: {
      street: 'Tower B, 3rd Floor, Unitech Cyber Park, Durga Colony, Sector 39',
      locality: 'Gurugram',
      region: 'Haryana',
      postalCode: '122002',
      country: 'IN',
    },
    // Unitech Cyber Park, Sector 39, Gurugram. Building-level, not a survey point.
    geo: { lat: 28.4419, lng: 77.0483 },
    areasServed: ['Cyber City', 'Udyog Vihar', 'Golf Course Road', 'Sohna Road', 'Sector 39', 'MG Road', 'IMT Manesar'],
    localNote:
      'Our head office is at Unitech Cyber Park in Sector 39, a short drive from Cyber City and the Golf Course Road corridor, so client workshops and review sessions happen in person rather than over video.',
  },

  rohtak: {
    key: 'rohtak',
    city: 'Rohtak',
    label: 'Rohtak',
    // Client-confirmed as a real, staffed second office.
    confirmed: true,
    schemaReady: true,
    address: {
      street: '106, First Floor, Agro Mall',
      locality: 'Rohtak',
      region: 'Haryana',
      // ⚠️ PIN pending client confirmation. postalCode is recommended rather
      // than required by schema.org, so LocalBusiness still validates without
      // it — but add it as soon as it is confirmed, because Google Business
      // Profile matching is stricter than schema validation.
      postalCode: '',
      country: 'IN',
    },
    geo: { lat: 28.8955, lng: 76.6066 },
    areasServed: ['IMT Rohtak', 'Delhi Road commercial belt', 'Model Town', 'Sector 14 institutional area'],
    localNote:
      'We have an office in Rohtak, which is unusual for a digital agency — most serve Haryana remotely from Delhi or Gurugram. It means local institutes, hospitals, IMT manufacturers and retailers get face-to-face project reviews.',
  },

  // ── SELL-ONLY MARKETS ─────────────────────────────────────────────────────
  // We sell into and deliver to these. We do NOT claim a physical office in any
  // of them until the client confirms a real, staffed premises in writing.
  // localNote copy below therefore describes delivery, never a location.
  noida: {
    key: 'noida',
    city: 'Noida',
    label: 'Noida',
    confirmed: false,
    schemaReady: false,
    address: null,
    areasServed: ['Sector 62', 'Sector 63', 'Sector 16A Film City', 'Sector 125–132 expressway corridor'],
    localNote:
      'We work with clients across the Sector 62–63 IT belt, Film City and the expressway corridor. Delivery is from our Gurugram head office, roughly an hour away, so on-site meetings are practical when a project needs them.',
  },
  mumbai: {
    key: 'mumbai',
    city: 'Mumbai',
    label: 'Mumbai',
    // Client has confirmed this IS a real office, but the street address is
    // still pending. Until it arrives we render sell-only copy: no address, no
    // map, no LocalBusiness schema. Google Business Profile matching needs an
    // exact address, and publishing an approximate one is worse than waiting.
    // Flip `confirmed` and fill `address` together — never separately.
    confirmed: false,
    realPendingAddress: true,
    schemaReady: false,
    address: null,
    areasServed: ['Bandra Kurla Complex (BKC)', 'Lower Parel', 'Andheri East (MIDC and SEEPZ)', 'Powai'],
    localNote:
      'We work with BFSI, media and D2C clients across BKC, Lower Parel and Andheri East, on IST alongside you.',
  },
  dubai: {
    key: 'dubai',
    city: 'Dubai',
    label: 'Dubai',
    confirmed: false,
    schemaReady: false,
    international: true,
    currency: 'AED',
    address: null,
    areasServed: ['Business Bay', 'DMCC and Jumeirah Lakes Towers', 'Dubai Internet City', 'Deira'],
    localNote:
      'We work with real estate, trading, hospitality and logistics businesses across the Emirates. Delivery is from our India team — Dubai runs 1.5 hours behind IST, so the working day overlaps almost entirely, and we invoice in AED.',
  },
};

/** Offices we can legitimately publish an address and map for. */
function publishableOffices() {
  return Object.values(OFFICES).filter((o) => o.confirmed && o.schemaReady && o.address);
}

/** Confirmed, staffed premises — the only ones that may claim a location. */
function confirmedOffices() {
  return Object.values(OFFICES).filter((o) => o.confirmed);
}

/** True when we may make any "we have an office here" claim about this key. */
function hasConfirmedOffice(locationKey) {
  const o = officeFor(locationKey);
  return !!(o && o.confirmed);
}

/**
 * Human-readable list of confirmed office cities, for copy that would otherwise
 * hardcode "Gurugram, Noida, Rohtak, Mumbai and Dubai". Derived, so it shrinks
 * or grows automatically as offices are confirmed.
 */
function confirmedOfficeCities() {
  const cities = confirmedOffices().map((o) => o.city);
  if (cities.length === 0) return '';
  if (cities.length === 1) return cities[0];
  return cities.slice(0, -1).join(', ') + ' and ' + cities[cities.length - 1];
}

/** Look up an office by location key, following the gurugram/gurgaon alias. */
function officeFor(locationKey) {
  if (!locationKey) return null;
  const key = String(locationKey).toLowerCase() === 'gurugram' ? 'gurgaon' : String(locationKey).toLowerCase();
  return OFFICES[key] || null;
}

/** A Google Maps embed URL. Uses the query form so no API key is needed. */
function mapEmbedUrl(office) {
  if (!office || !office.address) return null;
  const a = office.address;
  const q = [a.street, a.locality, a.region, a.postalCode, 'India'].filter(Boolean).join(', ');
  return `https://www.google.com/maps?q=${encodeURIComponent(q)}&output=embed`;
}

/** A plain "get directions" link, safe to show even without an embed. */
function mapLinkUrl(office) {
  if (!office) return null;
  const a = office.address;
  const q = a
    ? [NAP.name, a.street, a.locality, a.region, a.postalCode].filter(Boolean).join(', ')
    : `${NAP.name} ${office.city}`;
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
}

/** Single-line address for display. Null when we have no verified address. */
function formatAddress(office) {
  if (!office || !office.address) return null;
  const a = office.address;
  // postalCode may be pending (Rohtak) — do not emit a dangling region string.
  const regionLine = [a.region, a.postalCode].filter(Boolean).join(' ');
  return [a.street, a.locality, regionLine].filter(Boolean).join(', ');
}

/**
 * LocalBusiness JSON-LD for an office. Returns null unless we hold a verified
 * address — incomplete or invented LocalBusiness markup is worse than none.
 */
function localBusinessSchema(office, pageUrl) {
  // Three gates, all required. An unconfirmed location must never emit
  // LocalBusiness markup — that is what triggers GBP suspensions.
  if (!office || !office.confirmed || !office.schemaReady || !office.address) return null;
  const a = office.address;
  return {
    '@context': 'https://schema.org',
    '@type': 'ProfessionalService',
    '@id': `${NAP.url}/#office-${office.key}`,
    name: office.isHQ ? NAP.name : `${NAP.name} — ${office.city}`,
    url: pageUrl || NAP.url,
    telephone: NAP.phone,
    email: NAP.email,
    parentOrganization: { '@id': `${NAP.url}/#organization` },
    address: Object.assign(
      {
        '@type': 'PostalAddress',
        streetAddress: a.street,
        addressLocality: a.locality,
        addressRegion: a.region,
        addressCountry: a.country,
      },
      // Omit rather than emit an empty string while a PIN is pending.
      a.postalCode ? { postalCode: a.postalCode } : {}
    ),
    geo: office.geo
      ? { '@type': 'GeoCoordinates', latitude: office.geo.lat, longitude: office.geo.lng }
      : undefined,
    areaServed: (office.areasServed || []).map((n) => ({ '@type': 'Place', name: n })),
    openingHoursSpecification: [
      {
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: NAP.openingHours.days,
        opens: NAP.openingHours.opens,
        closes: NAP.openingHours.closes,
      },
    ],
    sameAs: NAP.sameAs,
    // Deliberately no aggregateRating — see SEO-RECOVERY.md §4.1.
  };
}

/* DATA-END */

export {
  NAP,
  OFFICES,
  officeFor,
  publishableOffices,
  confirmedOffices,
  confirmedOfficeCities,
  hasConfirmedOffice,
  mapEmbedUrl,
  mapLinkUrl,
  formatAddress,
  localBusinessSchema,
};
