// AUTO-GENERATED by generate-sitemap.cjs — do not edit.
// Source of truth: src/data/offices.js

/**
 * offices.js — single source of truth for Avani Enterprises NAP data.
 *
 * WHY THIS EXISTS
 * ---------------
 * The codebase carried THREE different Gurugram addresses:
 *   1. Footer.tsx          "3rd Floor, Tower-B, Cyber Park, Durga Colony,
 *                           Sector 39, Gurugram, Haryana 122001"
 *   2. website-content.md  "Tower B, 3rd Floor, Unitech Cyber Park, Sector 39,
 *                           Gurugram, Haryana 122002"   (same building, different PIN)
 *   3. LocalServicePage /  "DLF Cyber City, Gurugram"    (a DIFFERENT part of the city)
 *      cityPagesData.ts
 * …and the phone number appeared in five formats.
 *
 * NAP (Name, Address, Phone) consistency is a direct local-pack ranking factor:
 * Google cross-references your website against your Google Business Profile and
 * third-party citations, and conflicting addresses suppress local rankings. One
 * file now owns this, and everything else reads from it.
 *
 * ⚠️ CLIENT ACTION REQUIRED — see SEO-RECOVERY.md §4
 *   • Confirm which Gurugram address and PIN code is correct. We have used the
 *     Footer version (most recently committed, and the one with a live Maps
 *     link). If it is wrong, fix it HERE and everywhere updates.
 *   • Supply real street addresses for Noida, Rohtak, Mumbai and Dubai. Until
 *     then those offices deliberately emit NO LocalBusiness schema and NO map —
 *     publishing an address we cannot verify would be worse than publishing none.
 *
 * `schemaReady` gates schema + map emission. It is true only when we hold a
 * verifiable street address. Do not set it true to "fill in the gap".
 */

/* DATA-START */

const NAP = {
  name: 'Avani Enterprises',
  url: 'https://www.avanienterprises.in',
  // One canonical phone format everywhere. E.164 for tel:/schema, spaced for display.
  phone: '+919253625099',
  phoneDisplay: '+91 92536 25099',
  email: 'kp@avanienterprises.in',
  sameAs: [
    'https://www.linkedin.com/company/avani-enterprises-india',
    'https://www.instagram.com/avanienterprises.branding/',
    'https://twitter.com/avanienterprises',
    'https://www.facebook.com/share/1DKFWQiBe4/',
  ],
  openingHours: {
    days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    opens: '09:00',
    closes: '19:00',
  },
};

const OFFICES = {
  gurgaon: {
    key: 'gurgaon',
    city: 'Gurugram',
    label: 'Gurugram (Head Office)',
    isHQ: true,
    schemaReady: true,
    address: {
      street: '3rd Floor, Tower-B, Cyber Park, Durga Colony, Sector 39',
      locality: 'Gurugram',
      region: 'Haryana',
      postalCode: '122001',
      country: 'IN',
    },
    // Sector 39 / Cyber Park, Gurugram. Approximate to the building, not a survey point.
    geo: { lat: 28.4419, lng: 77.0483 },
    areasServed: ['Cyber City', 'Udyog Vihar', 'Golf Course Road', 'Sohna Road', 'Sector 39', 'MG Road', 'IMT Manesar'],
    localNote:
      'Our head office is on the Sector 39 Cyber Park side of Gurugram, a short drive from Cyber City and the Golf Course Road corridor, so client workshops and review sessions happen in person rather than over video.',
  },

  // ── Offices confirmed by the client but with no verified street address yet ──
  // schemaReady: false → no LocalBusiness schema, no map, no fabricated address.
  noida: {
    key: 'noida',
    city: 'Noida',
    label: 'Noida',
    schemaReady: false,
    address: null,
    areasServed: ['Sector 62', 'Sector 63', 'Sector 16A Film City', 'Sector 125–132 expressway corridor'],
    localNote:
      'Our Noida office covers the Sector 62–63 IT belt, Film City and the expressway corridor, so meetings do not require a trip across to Gurugram.',
  },
  rohtak: {
    key: 'rohtak',
    city: 'Rohtak',
    label: 'Rohtak',
    schemaReady: false,
    address: null,
    areasServed: ['IMT Rohtak', 'Delhi Road commercial belt', 'Model Town', 'Sector 14 institutional area'],
    localNote:
      'Having an office in Rohtak is unusual for a digital agency — most serve Haryana remotely from Delhi or Gurugram. It means local institutes, hospitals and IMT manufacturers get face-to-face project reviews.',
  },
  mumbai: {
    key: 'mumbai',
    city: 'Mumbai',
    label: 'Mumbai',
    schemaReady: false,
    address: null,
    areasServed: ['Bandra Kurla Complex (BKC)', 'Lower Parel', 'Andheri East (MIDC and SEEPZ)', 'Powai'],
    localNote:
      'Our Mumbai office covers the BFSI and media corridor — BKC, Lower Parel and Andheri East — with the delivery team on IST alongside you.',
  },
  dubai: {
    key: 'dubai',
    city: 'Dubai',
    label: 'Dubai',
    schemaReady: false,
    international: true,
    currency: 'AED',
    address: null,
    areasServed: ['Business Bay', 'DMCC and Jumeirah Lakes Towers', 'Dubai Internet City', 'Deira'],
    localNote:
      'Our Dubai office covers the UAE, backed by the India delivery team. Dubai runs 1.5 hours behind IST, so the working day overlaps almost entirely.',
  },
};

/** Offices we can legitimately publish an address and map for. */
function publishableOffices() {
  return Object.values(OFFICES).filter((o) => o.schemaReady && o.address);
}

/** Look up an office by location key, following the gurugram/gurgaon alias. */
function officeFor(locationKey) {
  if (!locationKey) return null;
  const key = String(locationKey).toLowerCase() === 'gurugram' ? 'gurgaon' : String(locationKey).toLowerCase();
  return OFFICES[key] || null;
}

/** A Google Maps embed URL. Uses the query form so no API key is needed. */
function mapEmbedUrl(office) {
  if (!office || !office.address) return null;
  const a = office.address;
  const q = [a.street, a.locality, a.region, a.postalCode, 'India'].filter(Boolean).join(', ');
  return `https://www.google.com/maps?q=${encodeURIComponent(q)}&output=embed`;
}

/** A plain "get directions" link, safe to show even without an embed. */
function mapLinkUrl(office) {
  if (!office) return null;
  const a = office.address;
  const q = a
    ? [NAP.name, a.street, a.locality, a.region, a.postalCode].filter(Boolean).join(', ')
    : `${NAP.name} ${office.city}`;
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
}

/** Single-line address for display. Null when we have no verified address. */
function formatAddress(office) {
  if (!office || !office.address) return null;
  const a = office.address;
  return [a.street, a.locality, `${a.region} ${a.postalCode}`].filter(Boolean).join(', ');
}

/**
 * LocalBusiness JSON-LD for an office. Returns null unless we hold a verified
 * address — incomplete or invented LocalBusiness markup is worse than none.
 */
function localBusinessSchema(office, pageUrl) {
  if (!office || !office.schemaReady || !office.address) return null;
  const a = office.address;
  return {
    '@context': 'https://schema.org',
    '@type': 'ProfessionalService',
    '@id': `${NAP.url}/#office-${office.key}`,
    name: office.isHQ ? NAP.name : `${NAP.name} — ${office.city}`,
    url: pageUrl || NAP.url,
    telephone: NAP.phone,
    email: NAP.email,
    parentOrganization: { '@id': `${NAP.url}/#organization` },
    address: {
      '@type': 'PostalAddress',
      streetAddress: a.street,
      addressLocality: a.locality,
      addressRegion: a.region,
      postalCode: a.postalCode,
      addressCountry: a.country,
    },
    geo: office.geo
      ? { '@type': 'GeoCoordinates', latitude: office.geo.lat, longitude: office.geo.lng }
      : undefined,
    areaServed: (office.areasServed || []).map((n) => ({ '@type': 'Place', name: n })),
    openingHoursSpecification: [
      {
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: NAP.openingHours.days,
        opens: NAP.openingHours.opens,
        closes: NAP.openingHours.closes,
      },
    ],
    sameAs: NAP.sameAs,
    // Deliberately no aggregateRating — see SEO-RECOVERY.md §4.1.
  };
}

/* DATA-END */

export {
  NAP,
  OFFICES,
  officeFor,
  publishableOffices,
  mapEmbedUrl,
  mapLinkUrl,
  formatAddress,
  localBusinessSchema,
};
