// AUTO-GENERATED by generate-sitemap.cjs — do not edit.
// Source of truth: src/data/comparisons.js

/**
 * comparisons.js — honest competitor comparison content for the *-alternative pages.
 *
 * WHY THIS EXISTS
 * ---------------
 * The original comparison tables scored Avani positive on every single row, and
 * every competitor cell read "Contact them for details". That is not a
 * comparison — it is an advertisement in the shape of one. It fails users
 * searching "<competitor> alternative" (who want a real trade-off, not a pitch),
 * and it is the pattern Google's helpful-content guidance calls out as
 * search-engine-first content.
 *
 * The rules this file follows:
 *
 *   1. EVERY comparison names at least one thing the competitor does better.
 *      A page that cannot do this has no credibility and will not convert.
 *   2. NO invented facts about competitors. Claims are limited to publicly
 *      stated positioning, which is stable and checkable. Where we do not know
 *      something, we say we do not know and point the reader at the vendor —
 *      we never guess at their pricing, headcount or client numbers.
 *   3. Claims about US are things we can back: our offices, our stack, our
 *      engagement model.
 *   4. Each entry carries `reviewedOn`. Competitor positioning changes; stale
 *      comparison content is a liability. Re-check on the cadence in
 *      SEO-RECOVERY.md.
 *
 * ⚠️ CLIENT ACTION: read the `theirStrength` and `betterFor` lines below and
 * confirm you are comfortable publishing them. They are deliberately generous to
 * competitors — that is what makes the rest of the page believable.
 */

/* DATA-START */

// Bump when the competitor claims on this page are re-verified.
const REVIEWED_ON = '2026-07';

const COMPARISONS = {
  // ── HR / payroll SaaS ─────────────────────────────────────────────────────
  // Compared against Avani Business OS (a built-for-you platform), not against
  // an agency retainer. The honest axis is buy-vs-build, not "we are better".
  'keka-alternative': {
    competitor: 'Keka',
    category: 'hr-saas',
    theirPositioning: 'A mid-market HR and payroll SaaS platform, widely used in India and known for a polished employee-facing experience.',
    theirStrength: 'You can sign up and be running in days without any development work, and Keka maintains the product and its statutory updates for you.',
    betterFor: 'Teams that want a proven product now, have standard HR processes, and would rather pay per employee than own software.',
    ourDifference: 'Avani Business OS is built for you and deployed on your infrastructure, so there is no per-seat licence and you own the source code and the data.',
    betterForUs: 'Companies whose HR or payroll process does not fit a standard product, or whose per-seat cost has become significant as headcount grows.',
    rows: [
      { metric: 'Time to go live', avani: 'Weeks — it is a build, not a signup', competitor: 'Days — sign up and configure', winner: 'competitor' },
      { metric: 'Product maintenance', avani: 'We maintain it under a support agreement', competitor: 'Vendor maintains it as part of subscription', winner: 'competitor' },
      { metric: 'Published pricing', avani: 'Quoted after scoping — no public price list', competitor: 'Public per-employee pricing tiers', winner: 'competitor' },
      { metric: 'Cost as headcount grows', avani: 'Flat — no per-seat licence', competitor: 'Scales with employee count', winner: 'avani' },
      { metric: 'Fit to non-standard process', avani: 'Built around your actual process', competitor: 'Your process adapts to the product', winner: 'avani' },
      { metric: 'Source code and data ownership', avani: 'Yours, on your infrastructure', competitor: 'Vendor-hosted SaaS', winner: 'avani' },
    ],
    verdict: 'If your HR process is standard and you want it working next week, Keka is the sensible choice and we will say so. Talk to us when per-seat cost has become a real line item, or when a core process keeps having to bend to fit the product.',
  },

  'greythr-alternative': {
    competitor: 'greytHR',
    category: 'hr-saas',
    theirPositioning: 'A long-established Indian HR and payroll platform with a strong focus on statutory payroll and compliance for small and mid-sized businesses.',
    theirStrength: 'Years of accumulated Indian payroll and compliance handling, kept current by the vendor as regulations change — that is a genuine moat and a real cost saving.',
    betterFor: 'Small and mid-sized businesses that mainly need compliant payroll, run standard processes, and do not want to own software.',
    ourDifference: 'We build the platform around your operations and connect payroll to the rest of your business — CRM, projects, finance — in one system rather than one more subscription.',
    betterForUs: 'Businesses that need HR and payroll joined to operations that a standalone payroll product does not reach.',
    rows: [
      { metric: 'Statutory compliance updates', avani: 'We update it under a support agreement', competitor: 'Vendor-maintained as part of the subscription', winner: 'competitor' },
      { metric: 'Setup effort', avani: 'A build project', competitor: 'Configure and go', winner: 'competitor' },
      { metric: 'Track record on Indian payroll edge cases', avani: 'Built per client', competitor: 'Long-established, broad accumulated coverage', winner: 'competitor' },
      { metric: 'Integration with your other operations', avani: 'One system across HR, CRM, projects and finance', competitor: 'Focused on HR and payroll', winner: 'avani' },
      { metric: 'Per-employee cost at scale', avani: 'No per-seat licence', competitor: 'Subscription scales with headcount', winner: 'avani' },
      { metric: 'Customisation ceiling', avani: 'None — it is your codebase', competitor: 'Bounded by product configuration', winner: 'avani' },
    ],
    verdict: 'For straightforward compliant payroll, greytHR is a solid, proven choice. The case for building comes when payroll needs to talk to the rest of your operations, or when a standard product cannot express how you actually work.',
  },

  'darwinbox-alternative': {
    competitor: 'Darwinbox',
    category: 'hr-saas',
    theirPositioning: 'An enterprise HCM platform used by large organisations across Asia, covering the full employee lifecycle at scale.',
    theirStrength: 'Built for enterprise scale and complexity, with the implementation support, security posture and breadth that large organisations require.',
    betterFor: 'Large enterprises with thousands of employees, complex hierarchies and a procurement process that expects an established enterprise vendor.',
    ourDifference: 'We are the right size for companies below that threshold — a focused build, direct access to the people writing the code, and no enterprise licence.',
    betterForUs: 'Mid-sized companies for whom an enterprise HCM is over-specified and over-priced.',
    rows: [
      { metric: 'Enterprise scale and breadth', avani: 'Built to your scope', competitor: 'Full enterprise HCM breadth', winner: 'competitor' },
      { metric: 'Established enterprise vendor status', avani: 'A services partner, not a platform vendor', competitor: 'Recognised enterprise platform', winner: 'competitor' },
      { metric: 'Implementation support at scale', avani: 'Our own team', competitor: 'Dedicated enterprise implementation', winner: 'competitor' },
      { metric: 'Cost for a mid-sized company', avani: 'Scoped to what you need', competitor: 'Enterprise licensing', winner: 'avani' },
      { metric: 'Speed of change requests', avani: 'Direct to the engineers building it', competitor: 'Vendor roadmap and support process', winner: 'avani' },
      { metric: 'Ownership', avani: 'Your code, your infrastructure', competitor: 'Vendor-hosted platform', winner: 'avani' },
    ],
    verdict: 'If you are a large enterprise, Darwinbox is built for you and we are not going to pretend otherwise. We are a better fit below that scale, where enterprise HCM licensing buys breadth you will not use.',
  },

  'zoho-people-alternative': {
    competitor: 'Zoho People',
    category: 'hr-saas',
    theirPositioning: 'The HR module within the wider Zoho business suite, priced accessibly and integrated with the rest of the Zoho ecosystem.',
    theirStrength: 'Very low cost of entry, and if you already run Zoho CRM, Books or Desk, the integration between them is immediate and free of integration work.',
    betterFor: 'Businesses already committed to the Zoho ecosystem, or those wanting the lowest-cost route to basic HR software.',
    ourDifference: 'We build one system across HR, CRM and operations rather than joining modules, which matters when your workflow crosses those boundaries in ways a module boundary does not allow.',
    betterForUs: 'Companies not on Zoho, or those whose processes keep hitting the edges of what module configuration allows.',
    rows: [
      { metric: 'Entry cost', avani: 'A build investment up front', competitor: 'Low monthly subscription', winner: 'competitor' },
      { metric: 'If you already use Zoho', avani: 'We would integrate to it', competitor: 'Native, immediate', winner: 'competitor' },
      { metric: 'Time to first use', avani: 'Weeks', competitor: 'Same day', winner: 'competitor' },
      { metric: 'Depth of customisation', avani: 'Unbounded — it is your codebase', competitor: 'Bounded by module configuration', winner: 'avani' },
      { metric: 'Cost at higher headcount', avani: 'No per-user fee', competitor: 'Per-user, per-month', winner: 'avani' },
      { metric: 'Data ownership', avani: 'Your infrastructure', competitor: 'Vendor-hosted', winner: 'avani' },
    ],
    verdict: 'Zoho People is genuinely good value, especially inside the Zoho suite. Consider building when configuration limits start costing you more in workarounds than the software saves.',
  },

  // ── SEO / digital marketing agencies ──────────────────────────────────────
  // These are established Indian agencies. We compare on engagement model —
  // which is verifiable and matters to the buyer — not on invented performance.
  'techmagnate-alternative': {
    competitor: 'Techmagnate',
    category: 'seo-agency',
    theirPositioning: 'A long-established Indian digital marketing agency with a large team and a deep, SEO-focused specialism.',
    theirStrength: 'Scale and a long public track record in SEO specifically, with the bench depth to staff large, long-running campaigns.',
    betterFor: 'Large organisations that want a big, SEO-specialist agency with a long history and a substantial team behind the account.',
    ourDifference: 'We combine SEO with the engineering that most SEO fixes actually require — so a technical recommendation gets implemented by the same team rather than handed to your developers as a ticket.',
    betterForUs: 'Businesses whose SEO problems are technical — indexing, duplication, site architecture, Core Web Vitals — and who are tired of recommendations nobody implements.',
    rows: [
      { metric: 'Team size and bench depth', avani: 'Smaller, focused team', competitor: 'Large established agency', winner: 'competitor' },
      { metric: 'Length of public SEO track record', avani: 'Shorter as an SEO specialist', competitor: 'Long-established SEO specialism', winner: 'competitor' },
      { metric: 'SEO recommendations get implemented', avani: 'We implement them ourselves — we are the developers', competitor: 'Typically handed to your dev team', winner: 'avani' },
      { metric: 'Technical SEO plus engineering', avani: 'Same team does both', competitor: 'Verify their in-house dev capability directly', winner: 'avani' },
      { metric: 'Direct access to seniors', avani: 'Direct founder and engineer access', competitor: 'Account-managed', winner: 'avani' },
    ],
    verdict: 'If you want the largest possible SEO-specialist team, Techmagnate is a serious option. Choose us when your SEO problem is really an engineering problem and you need one team that can both diagnose and fix it.',
  },

  'pagetraffic-alternative': {
    competitor: 'PageTraffic',
    category: 'seo-agency',
    theirPositioning: 'One of India\'s longer-running SEO agencies, with an established search-marketing practice.',
    theirStrength: 'Longevity in search marketing and an established process built over many years of SEO-only focus.',
    betterFor: 'Businesses wanting a dedicated, long-established SEO agency with search as its single focus.',
    ourDifference: 'We are a build-and-market team — the website, the technical fixes and the campaigns come from one place, which removes the usual gap between recommendation and implementation.',
    betterForUs: 'Businesses that need the site rebuilt or fixed as part of the SEO work, not just optimised around.',
    rows: [
      { metric: 'Years focused purely on SEO', avani: 'Broader digital and engineering focus', competitor: 'Long-running SEO specialism', winner: 'competitor' },
      { metric: 'Single-discipline depth', avani: 'Multi-discipline by design', competitor: 'Concentrated on search', winner: 'competitor' },
      { metric: 'Can rebuild the site, not just advise on it', avani: 'Yes — in-house engineering', competitor: 'Verify their build capability directly', winner: 'avani' },
      { metric: 'Technical fixes turnaround', avani: 'Implemented by the same team', competitor: 'Depends on your developers', winner: 'avani' },
      { metric: 'AI and automation alongside SEO', avani: 'In-house', competitor: 'Confirm scope with them', winner: 'avani' },
    ],
    verdict: 'For pure search work with a long-established specialist, PageTraffic is a credible choice. We are the better fit when the site itself is part of the problem.',
  },

  'ez-rankings-alternative': {
    competitor: 'EZ Rankings',
    category: 'seo-agency',
    theirPositioning: 'An established Indian SEO and digital marketing agency serving domestic and international clients.',
    theirStrength: 'An established SEO practice with packaged service tiers, which makes scope and cost easy to compare up front.',
    betterFor: 'Businesses that want clearly packaged SEO deliverables at a predictable monthly price.',
    ourDifference: 'We scope from an audit rather than from a package, because the right first move differs enormously depending on whether your problem is indexing, duplication or authority.',
    betterForUs: 'Sites with a diagnosed structural problem, where a standard package would spend months on the wrong thing.',
    rows: [
      { metric: 'Packaged, easy-to-compare pricing', avani: 'Scoped per engagement', competitor: 'Published service tiers', winner: 'competitor' },
      { metric: 'Predictable monthly deliverable count', avani: 'Varies with what the audit finds', competitor: 'Fixed per package', winner: 'competitor' },
      { metric: 'Diagnosis before scope', avani: 'Audit first, then scope', competitor: 'Package first', winner: 'avani' },
      { metric: 'Engineering capability in-house', avani: 'Yes', competitor: 'Confirm with them directly', winner: 'avani' },
      { metric: 'Handles indexing and duplication problems', avani: 'Core specialism', competitor: 'Confirm scope with them', winner: 'avani' },
    ],
    verdict: 'If you want a predictable monthly SEO package, EZ Rankings makes that easy to buy. Come to us when you need a diagnosis first — particularly if Google is refusing to index your pages.',
  },

  'indeedseo-alternative': {
    competitor: 'IndeedSEO',
    category: 'seo-agency',
    theirPositioning: 'An Indian SEO and digital marketing agency offering search and online marketing services.',
    theirStrength: 'A dedicated search-marketing offering with packaged services for businesses that want SEO handled as a standalone line item.',
    betterFor: 'Businesses wanting SEO as a discrete, separately-managed service.',
    ourDifference: 'We treat SEO, the website and the ad campaigns as one system, because in practice they share the same landing pages, the same tracking and the same conversion problem.',
    betterForUs: 'Businesses that want one team accountable for the whole funnel rather than three vendors pointing at each other.',
    rows: [
      { metric: 'SEO as a standalone managed service', avani: 'Usually part of a wider engagement', competitor: 'Offered standalone', winner: 'competitor' },
      { metric: 'Single-discipline focus', avani: 'Multi-discipline', competitor: 'Search-focused', winner: 'competitor' },
      { metric: 'One team across SEO, site and ads', avani: 'Yes', competitor: 'Confirm their scope directly', winner: 'avani' },
      { metric: 'Implements its own technical recommendations', avani: 'Yes — in-house engineers', competitor: 'Confirm with them', winner: 'avani' },
      { metric: 'Conversion tracking and CRM wiring', avani: 'Built in', competitor: 'Confirm scope with them', winner: 'avani' },
    ],
    verdict: 'If you specifically want SEO bought and managed on its own, that is a legitimate model and IndeedSEO offers it. We are the better fit when you want one team accountable end to end.',
  },

  // ── Web / creative agencies ───────────────────────────────────────────────
  // We hold less public information about these. We say so rather than guess.
  'web-aspiration-alternative': {
    competitor: 'Web Aspiration',
    category: 'web-agency',
    theirPositioning: 'A web design and digital services agency.',
    theirStrength: 'A focused web and design offering. We do not hold enough verified detail on their current pricing, team or process to compare those fairly — ask them directly.',
    betterFor: 'Businesses whose need is primarily design and a straightforward website build, especially if they have an existing relationship there.',
    ourDifference: 'We add custom software, AI and performance marketing to the web build, and keep engineering in-house.',
    betterForUs: 'Projects where the website is one part of a larger system — custom back-end, CRM, automation or AI.',
    rows: [
      { metric: 'Focused web design offering', avani: 'Web design is one of several services', competitor: 'Concentrated web and design focus', winner: 'competitor' },
      { metric: 'Custom software and AI in-house', avani: 'Yes', competitor: 'Ask them directly — we cannot verify', winner: 'avani' },
      { metric: 'An office you can visit', avani: 'Yes — our Gurugram head office', competitor: 'Ask them directly', winner: 'avani' },
      { metric: 'Performance marketing alongside the build', avani: 'In-house', competitor: 'Ask them directly', winner: 'avani' },
    ],
    verdict: 'We are deliberately cautious here: we do not have verified detail on Web Aspiration\'s current offering, so compare us on what we state about ourselves and ask them the same questions.',
    lowConfidence: true,
  },

  'webmok-alternative': {
    competitor: 'Webmok',
    category: 'web-agency',
    theirPositioning: 'A web development and digital services provider.',
    theirStrength: 'A focused web development offering. We do not hold verified detail on their current scope, pricing or team — ask them directly.',
    betterFor: 'Businesses wanting a straightforward website build from a focused web shop.',
    ourDifference: 'In-house engineering across web, mobile, custom software and AI, with five offices and marketing under the same roof.',
    betterForUs: 'Projects that extend past a website into applications, automation or ongoing growth work.',
    rows: [
      { metric: 'Focused web development offering', avani: 'Broader service range', competitor: 'Concentrated web focus', winner: 'competitor' },
      { metric: 'Mobile apps in-house', avani: 'Yes — native and cross-platform', competitor: 'Ask them directly', winner: 'avani' },
      { metric: 'AI and automation', avani: 'In-house', competitor: 'Ask them directly', winner: 'avani' },
      { metric: 'Ongoing SEO and paid media', avani: 'In-house', competitor: 'Ask them directly', winner: 'avani' },
    ],
    verdict: 'We do not have verified detail on Webmok\'s current offering, so treat the competitor column as "unverified" rather than as a weakness, and ask them directly.',
    lowConfidence: true,
  },

  'leo-digitals-alternative': {
    competitor: 'Leo Digitals',
    category: 'web-agency',
    theirPositioning: 'A digital marketing and web services agency.',
    theirStrength: 'A digital marketing offering. We do not hold verified detail on their current services, team or pricing — ask them directly.',
    betterFor: 'Businesses with an existing relationship there, or who want a smaller, marketing-led partner.',
    ourDifference: 'Engineering and marketing in one team, with five offices and in-house AI capability.',
    betterForUs: 'Businesses that need the site or product built as well as marketed.',
    rows: [
      { metric: 'Marketing-led agency model', avani: 'Engineering plus marketing', competitor: 'Marketing-focused', winner: 'competitor' },
      { metric: 'In-house development', avani: 'Yes', competitor: 'Ask them directly', winner: 'avani' },
      { metric: 'AI services', avani: 'Chatbots, voice agents, agentic AI, AI video and content', competitor: 'Ask them directly', winner: 'avani' },
      { metric: 'An office you can visit', avani: 'Yes — our Gurugram head office', competitor: 'Ask them directly', winner: 'avani' },
    ],
    verdict: 'We cannot verify Leo Digitals\' current offering in enough detail to compare fairly. Judge us on what we state about ourselves and put the same questions to them.',
    lowConfidence: true,
  },

  'the-growth-box-alternative': {
    competitor: 'The Growth Box',
    category: 'web-agency',
    theirPositioning: 'A growth and digital marketing agency.',
    theirStrength: 'A growth-marketing focus. We do not hold verified detail on their current services or pricing — ask them directly.',
    betterFor: 'Businesses wanting a dedicated growth-marketing partner without an engineering component.',
    ourDifference: 'We pair growth work with the engineering to implement it, and run both from one team.',
    betterForUs: 'Businesses where growth is blocked by the product or the site rather than by the campaigns.',
    rows: [
      { metric: 'Dedicated growth-marketing focus', avani: 'Growth plus engineering', competitor: 'Growth-focused', winner: 'competitor' },
      { metric: 'Builds the pages and product it markets', avani: 'Yes', competitor: 'Ask them directly', winner: 'avani' },
      { metric: 'Conversion tracking and CRM integration', avani: 'Built in-house', competitor: 'Ask them directly', winner: 'avani' },
      { metric: 'AI capability', avani: 'In-house', competitor: 'Ask them directly', winner: 'avani' },
    ],
    verdict: 'If your growth problem is purely a marketing problem, a dedicated growth agency is a reasonable choice. We are the better fit when the constraint is the site or the product itself.',
    lowConfidence: true,
  },
};

function comparisonFor(pathname) {
  const slug = String(pathname || '').toLowerCase().replace(/^\/+/, '').replace(/\/+$/, '');
  const entry = COMPARISONS[slug];
  return entry ? Object.assign({ slug, reviewedOn: REVIEWED_ON }, entry) : null;
}

/* DATA-END */

export { COMPARISONS, REVIEWED_ON, comparisonFor };
